#!/usr/bin/env python3
"""Select an imported compiler and generate the Ninja build graph."""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
import tempfile
from pathlib import Path

from tools import assets, host, modules, toolchain
from tools.common import ROOT, InputError, read_json, source_inventory, write_bytes, write_json


def ninja_path(value: str) -> str:
    if "\n" in value or "\r" in value:
        raise InputError("Build paths cannot contain newlines.")
    return value.replace("$", "$$").replace(" ", "$ ").replace(":", "$:")


def command_line(parts: list[str]) -> str:
    command = subprocess.list2cmdline(parts) if os.name == "nt" else shlex.join(parts)
    return command.replace("$", "$$")


def edge(outputs: list[str], rule: str, inputs: list[str] = (), implicit: list[str] = ()) -> str:
    """Wrap long generated dependency lists so individual paths remain readable."""
    words = [*(ninja_path(p) for p in outputs)]
    line = "build " + " ".join(words) + ": " + rule
    dependencies = [*(ninja_path(p) for p in inputs)]
    if implicit:
        dependencies.extend(["|", *(ninja_path(p) for p in implicit)])
    lines = []
    for word in dependencies:
        if len(line) + len(word) > 100:
            lines.append(line + " $")
            line = "  " + word
            continue
        line += " " + word
    return "\n".join([*lines, line])


def generate(settings: dict, config: dict) -> bytes:
    version = settings["toolchain"]
    output = f"build/{version}"
    source_files = source_inventory()
    config = modules.resolve(config, source_files)
    shared = [name for name in source_files if not name.startswith(("src/", "include/"))]
    headers = [name for name in source_files if name.startswith("include/")]
    compiler_files = [f".local/toolchains/{version}/{name}" for name in settings["tool_files"]]
    launcher_files = (
        [settings["launcher"]["path"]] if settings["launcher"]["name"] == "wibo" else []
    )
    manifest = read_json(ROOT / "config/artwork.json")
    artwork_files = [
        p.relative_to(ROOT).as_posix() for p in assets.resolved_inputs(ROOT, manifest).values()
    ]
    watched_roots = [
        "src",
        "include",
        "config",
        "tools",
        "assets",
        f".local/toolchains/{version}/bin",
        f".local/toolchains/{version}/include",
    ]
    directories = [
        name
        for folder in watched_roots
        for name in [
            folder,
            *(
                p.relative_to(ROOT).as_posix()
                for p in (ROOT / folder).rglob("*")
                if p.is_dir() and "__pycache__" not in p.parts
            ),
        ]
    ]
    discovered = list(
        dict.fromkeys(
            [*source_files, *compiler_files, *artwork_files, *launcher_files, *directories]
        )
    )
    python = command_line([sys.executable])
    reconfigure = command_line(
        [sys.executable, "configure.py", "--toolchain", version, "--offline"]
    )
    lines = [
        "# Generated by configure.py from src/ and config/build.json.",
        "ninja_required_version = 1.10",
        f"builddir = {output}",
        "pool producer",
        "  depth = 1",
        "rule step",
        f"  command = {python} -m tools.build {version} $action",
        "  description = $label",
        "  pool = producer",
        "rule configure",
        f"  command = {reconfigure}",
        "  description = CONFIGURE",
        "  generator = 1",
        edge(["build.ninja"], "configure", [".local/config.json", *discovered]),
        # Shared phony targets keep dependency sets in one place in the graph.
        edge(
            ["build_inputs"],
            "phony",
            [
                ".local/config.json",
                *shared,
                *(
                    p
                    for p in directories
                    if p == "tools"
                    or p.startswith("tools/")
                    or p == "config"
                    or p.startswith("config/")
                ),
            ],
        ),
        edge(["compiler_inputs"], "phony", [*compiler_files, *launcher_files]),
        edge(
            ["headers"],
            "phony",
            [*headers, *(p for p in directories if p == "include" or p.startswith("include/"))],
        ),
        edge(
            ["artwork_inputs"],
            "phony",
            [*artwork_files, "assets", "assets/local", "assets/placeholders"],
        ),
        edge(
            [f"{output}/rom_assets.h", f"{output}/artwork.json"],
            "step",
            ["artwork_inputs"],
            ["build_inputs"],
        ),
        "  action = artwork",
        "  label = CONVERT artwork",
        edge(
            [f"{output}/runtime.lib", f"{output}/runtime.json", f"{output}/runtime.log"],
            "step",
            implicit=["build_inputs", "compiler_inputs"],
        ),
        "  action = runtime",
        "  label = LBG runtime",
    ]
    objects, records = [], []
    for module, source in config["modules"].items():
        stem = f"{output}/{module}"
        objects.append(f"{stem}.obj")
        records.append(f"{stem}.json")
        inputs = [f"src/{source['file']}", "headers"]
        if module == modules.ARTWORK_MODULE:
            inputs.extend([f"{output}/rom_assets.h", f"{output}/artwork.json"])
        lines.extend(
            [
                edge(
                    [f"{stem}.obj", f"{stem}.json", f"{stem}.log"],
                    "step",
                    inputs,
                    ["build_inputs", "compiler_inputs"],
                ),
                "  action = " + command_line(["compile", module, "--source", source["file"]]),
                f"  label = CH38 {source['file']}",
            ]
        )
    lines.extend(
        [
            edge(
                [
                    f"{output}/{name}"
                    for name in (
                        "pw.bin",
                        "pw.map",
                        "link.sub",
                        "link.json",
                        "link.log",
                        "build.json",
                    )
                ],
                "step",
                [
                    *objects,
                    *records,
                    f"{output}/runtime.lib",
                    f"{output}/runtime.json",
                    f"{output}/rom_assets.h",
                    f"{output}/artwork.json",
                    *source_files,
                    *(p for p in directories if p == "src" or p.startswith("src/")),
                ],
                ["build_inputs", "compiler_inputs"],
            ),
            "  action = link",
            "  label = LINK pw.bin",
            "build always: phony",
        ]
    )
    for action, receipt in (("status", "status.json"), ("verify", "verified.json")):
        inputs = (
            [f"{output}/status.json"]
            if action == "verify"
            else [f"{output}/pw.bin", f"{output}/build.json", f"{output}/link.json", "always"]
        )
        lines.extend(
            [
                edge(
                    [f"{output}/{receipt}"],
                    "step",
                    inputs,
                    ["build_inputs", "compiler_inputs"],
                ),
                f"  action = {action}",
                "  label = CHECK retail SHA-256"
                if action == "status"
                else "  label = VERIFY retail SHA-256",
            ]
        )
    lines.extend(
        [
            f"build firmware: phony {output}/pw.bin",
            f"build verify: phony {output}/verified.json",
            f"default {output}/status.json",
            "",
            "# Allow graph regeneration when a discovered file or directory is removed.",
            *(edge([path], "phony") for path in discovered),
            "",
        ]
    )
    return "\n".join(lines).encode("utf-8")


def select_suite(requested: str | None, previous: dict) -> str:
    selected = requested or previous.get("toolchain")
    if selected:
        return toolchain.validate_name(selected)
    directory = ROOT / ".local/toolchains"
    available = (
        sorted(p.name for p in directory.iterdir() if p.is_dir() and (p / "bin/ch38.exe").is_file())
        if directory.is_dir()
        else []
    )
    if len(available) == 1:
        return available[0]
    if available:
        raise InputError("Select a compiler with --toolchain NAME: " + ", ".join(available))
    raise InputError("Import a compiler first: uv run -m tools.toolchain import PATH")


def configure(args) -> None:
    os.chdir(ROOT)
    local = ROOT / ".local"
    settings_file = local / "config.json"
    previous = read_json(settings_file) if settings_file.is_file() else {}
    version = select_suite(args.toolchain, previous)
    suite = toolchain.describe(local / "toolchains" / version)
    for warning in suite["warnings"]:
        print(f"Warning: {warning}", file=sys.stderr)
    override = args.wibo or os.environ.get("PW_WIBO") or previous.get("wibo")
    if args.managed_wibo:
        override = None
    launcher = host.select(override, args.offline)
    scratch = (
        args.work_dir
        or previous.get("work_dir")
        or ("/tmp" if sys.platform == "darwin" else tempfile.gettempdir())
    )
    scratch = Path(scratch).expanduser().resolve()
    if not str(scratch).isascii() or not scratch.is_dir():
        raise InputError("Supply --work-dir PATH to an existing, writable ASCII directory.")
    with tempfile.TemporaryDirectory(prefix="pw-check-", dir=scratch):
        pass
    settings = {
        "toolchain": version,
        "tool_files": suite["files"],
        "qualified_version": suite["qualified_version"],
        "launcher": launcher,
        "work_dir": str(scratch),
    }
    if override and launcher["name"] == "wibo":
        settings["wibo"] = launcher["path"]
    (ROOT / "assets/local").mkdir(parents=True, exist_ok=True)
    graph = generate(settings, read_json(ROOT / "config/build.json"))
    old_settings = settings_file.read_bytes() if settings_file.exists() else None
    try:
        if settings != previous:
            write_json(settings_file, settings)
        write_bytes(ROOT / "build.ninja", graph)
    except OSError:
        if old_settings is None:
            settings_file.unlink(missing_ok=True)
        else:
            write_bytes(settings_file, old_settings)
        raise
    print(
        f"Configured {version}. Run uv run ninja to build; uv run ninja verify checks retail identity."
    )
    if not host.qualified_host():
        print("Warning: this host combination is unverified; see docs/build.md.", file=sys.stderr)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--toolchain", help="name of an imported compiler (see tools.toolchain list)"
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--wibo", help="use an existing Wibo executable")
    group.add_argument("--managed-wibo", action="store_true", help="use the managed Wibo download")
    parser.add_argument("--offline", action="store_true", help="never download a missing host tool")
    parser.add_argument(
        "--work-dir", type=Path, help="ASCII directory for private compiler scratch files"
    )
    try:
        configure(parser.parse_args())
    except (InputError, OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"Error: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
